[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "c2526-r1"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "asttokens==3.0.1",
    "beautifulsoup4==4.14.3",
    "bertopic>=0.17.4",
    "branca==0.8.2",
    "bs4==0.0.2",
    "certifi==2026.1.4",
    "cffi==2.0.0",
    "chardet>=7.0.1",
    "charset-normalizer==3.4.4",
    "cloudpickle==3.1.2",
    "colorama==0.4.6",
    "comm==0.2.3",
    "cryptography==46.0.4",
    "debugpy==1.8.19",
    "decorator==5.2.1",
    "executing==2.2.1",
    "farama-notifications==0.0.4",
    "fastapi>=0.135.3",
    "fastparquet>=2025.12.0",
    "folium==0.20.0",
    "ftfy==6.3.1",
    "gensim>=4.4.0",
    "google-api-core==2.29.0",
    "google-api-python-client==2.188.0",
    "google-auth==2.48.0",
    "google-auth-httplib2==0.3.0",
    "googleapis-common-protos==1.72.0",
    "gymnasium==1.2.2",
    "httplib2==0.31.2",
    "idna==3.11",
    "ipykernel==7.1.0",
    "ipython==9.9.0",
    "ipython-pygments-lexers==1.1.1",
    "ipywidgets==8.1.8",
    "isodate>=0.7.2",
    "jedi==0.19.2",
    "jinja2==3.1.6",
    "jupyter-client==8.8.0",
    "jupyter-core==5.9.1",
    "jupyterlab-widgets==3.0.16",
    "langcodes==3.5.1",
    "locate==1.1.1",
    "markupsafe==3.0.3",
    "matplotlib>=3.10.8",
    "matplotlib-inline==0.2.1",
    "minio>=7.2.20",
    "msgpack==1.1.2",
    "nest-asyncio==1.6.0",
    "nltk>=3.9.3",
    "numpy==2.4.2",
    "optuna==4.2.1",
    "packaging==26.0",
    "pandas==3.0.0",
    "parso==0.8.5",
    "platformdirs==4.5.1",
    "prompt-toolkit==3.0.52",
    "proto-plus==1.27.0",
    "protobuf==6.33.4",
    "psutil==7.2.2",
    "pure-eval==0.2.3",
    "pyarrow>=23.0.1",
    "pyasn1==0.6.2",
    "pyasn1-modules==0.4.2",
    "pycparser==3.0",
    "pygments==2.19.2",
    "pyparsing==3.3.2",
    "python-dateutil==2.9.0.post0",
    "pytube==15.0.0",
    "pyzmq==27.1.0",
    "regex==2026.1.15",
    "requests==2.32.5",
    "rsa==4.9.1",
    "scikit-learn>=1.8.0",
    "seaborn>=0.13.2",
    "selenium>=4.41.0",
    "sentence-transformers>=5.2.3",
    "six==1.17.0",
    "soupsieve==2.8.3",
    "spacy>=3.8.11",
    "stack-data==0.6.3",
    "tornado==6.5.4",
    "tqdm>=4.67.3",
    "traitlets==5.14.3",
    "typing-extensions==4.15.0",
    "tzdata==2025.3",
    "uritemplate==4.2.0",
    "urllib3==2.6.3",
    "uvicorn>=0.44.0",
    "wandb>=0.25.1",
    "wcwidth==0.5.0",
    "weave>=0.52.31",
    "widgetsnbextension==4.0.15",
    "wonderwords>=3.0.1",
    "wordfreq==3.1.1",
    "xgboost>=3.2.0",
    "xyzservices==2025.11.0",
    "yt-dlp==2026.1.31",
]

#[tool.hatch.build.targets.wheel]
#packages = [
#    "src/comun",
#    "src/extraccion"
#    ]

[tool.uv.workspace]
members = [
    "src/comun",
    "src/extraccion",
]

[tool.uv.sources]
comun = { workspace = true }
extraccion = { workspace = true }

[dependency-groups]
app = [
    "comun",
    "extraccion",
    "fastapi>=0.135.3",
    "google-api-python-client>=2.188.0",
    "jinja2>=3.1.6",
    "joblib>=1.5.3",
    "minio>=7.2.20",
    "pandas>=3.0.0",
    "scikit-learn>=1.8.0",
    "uvicorn>=0.44.0",
    "yt-dlp>=2026.1.31",
]
